### ISSUE TITLE
[BUG] EdXposed Broken on Android 11 (R)

### ISSUE THREAD

**Issue by Justsnoopy30** [ElderDrivers/EdXposed#534] opened 2020-05-07 14:15 UTC
Moved from EdXposed Manager Repo.

Riru - Core Version: v21.1
EdXposed Version: v0.5.0.0
Android Version: 11 (R)
Device Manufacturer: Google
Device Name: Pixel 3 XL
EdXposed Manager Version: 4.5.7

```
--------- beginning of head
EdXposed Log
Powered by Log Catcher
QQ support group: 855219808
Telegram support group: @Code_Of_MeowCat
Telegram channel: @EdXposed
--------- beginning of information
Manufacturer: Google
Brand: google
Device: crosshatch
Product: crosshatch
Model: Pixel 3 XL
Fingerprint: google/crosshatch/crosshatch:10/RPP3.200320.017/6412707:user/release-keys
ROM description: crosshatch-user R RPP3.200320.017 6412707 release-keys
Architecture: arm64-v8a
Android build: RPP3.200320.017
Android version: 10
Android sdk: 29
EdXposed version: v0.5.0.0 (4548) (SandHook)
EdXposed api: 91.0
Riru version: v21.1 (34)
Riru api: 6
Magisk:  ()
--------- beginning of main
--------- beginning of system
05-02 10:18:21.786  1089  1089 I EdXposed: onModuleLoaded: welcome to EdXposed!
05-02 10:18:21.786  1089  1089 I EdXposed: Start to install inline hooks
05-02 10:18:21.786  1089  1089 I EdXposed: Using api level 29
05-02 10:18:21.786  1089  1089 I EdXposed: Start to install Riru hook
05-02 10:18:21.804  1089  1089 I EdXposed: Riru hooks installed
05-02 10:18:21.851  1089  1089 I EdXposed: dlopen hooked
05-02 10:18:21.957  1089  1089 I EdXposed: using installer org.meowcat.edxposed.manager
05-02 10:18:21.957  1089  1089 I EdXposed: data path prefix: /data/user_de/0/
05-02 10:18:21.957  1089  1089 I EdXposed:   application list mode: true
05-02 10:18:21.957  1089  1089 I EdXposed:     using whitelist: false
05-02 10:18:21.957  1089  1089 I EdXposed:   dynamic modules mode: false
05-02 10:18:21.957  1089  1089 I EdXposed:   resources hook: true
05-02 10:18:21.957  1089  1089 I EdXposed:   deopt boot image: false
05-02 10:18:21.957  1089  1089 I EdXposed:   no module log: false
05-02 10:18:21.957  1089  1089 I EdXposed:   hidden api bypass: true
05-02 10:18:21.960  1089  1089 I EdXposed:   blacklist: com.google.android.gms
05-02 10:18:21.960  1089  1089 I EdXposed:   blacklist: com.google.android.gsf
05-02 10:18:21.973  1089  1089 I EdXposed: ART hooks installed
05-02 10:18:21.973  1089  1089 I EdXposed: system_property_get: dalvik.vm.dex2oat-filter -> quicken
05-02 10:18:21.973  1089  1089 I EdXposed: system_property_get: dalvik.vm.dex2oat-flags -> --inline-max-code-units=0
05-02 10:18:22.188  1090  1090 I EdXposed: onModuleLoaded: welcome to EdXposed!
05-02 10:18:22.188  1090  1090 I EdXposed: Start to install inline hooks
05-02 10:18:22.188  1090  1090 I EdXposed: Using api level 29
05-02 10:18:22.188  1090  1090 I EdXposed: Start to install Riru hook
05-02 10:18:22.203  1090  1090 I EdXposed: Riru hooks installed
05-02 10:18:22.227  1090  1090 I EdXposed: dlopen hooked
05-02 10:18:22.288  1090  1090 I EdXposed: using installer org.meowcat.edxposed.manager
05-02 10:18:22.288  1090  1090 I EdXposed: data path prefix: /data/user_de/0/
05-02 10:18:22.288  1090  1090 I EdXposed:   application list mode: true
05-02 10:18:22.288  1090  1090 I EdXposed:     using whitelist: false
05-02 10:18:22.288  1090  1090 I EdXposed:   dynamic modules mode: false
05-02 10:18:22.288  1090  1090 I EdXposed:   resources hook: true
05-02 10:18:22.288  1090  1090 I EdXposed:   deopt boot image: false
05-02 10:18:22.288  1090  1090 I EdXposed:   no module log: false
05-02 10:18:22.288  1090  1090 I EdXposed:   hidden api bypass: true
05-02 10:18:22.288  1090  1090 I EdXposed:   blacklist: com.google.android.gms
05-02 10:18:22.288  1090  1090 I EdXposed:   blacklist: com.google.android.gsf
05-02 10:18:22.294  1090  1090 I EdXposed: ART hooks installed
05-02 10:18:22.295  1090  1090 I EdXposed: system_property_get: dalvik.vm.dex2oat-filter -> quicken
05-02 10:18:22.295  1090  1090 I EdXposed: system_property_get: dalvik.vm.dex2oat-flags -> --inline-max-code-units=0
05-02 10:18:24.684  1616  1616 E EdXposed: error when hooking systemMain: pkg=android, prc=android
05-02 10:18:24.684  1616  1616 E EdXposed: java.lang.NoSuchMethodError: com.android.server.SystemServer#startBootstrapServices()#exact
05-02 10:18:24.684  1616  1616 E EdXposed: 	at de.robv.android.xposed.XposedHelpers.findMethodExact(XposedHelpers.java:344)
05-02 10:18:24.684  1616  1616 E EdXposed: 	at de.robv.android.xposed.XposedHelpers.findAndHookMethod(XposedHelpers.java:185)
05-02 10:18:24.684  1616  1616 E EdXposed: 	at de.robv.android.xposed.XposedHelpers.findAndHookMethod(XposedHelpers.java:260)
05-02 10:18:24.684  1616  1616 E EdXposed: 	at com.elderdrivers.riru.edxp.proxy.BaseRouter.startSystemServerHook(BaseRouter.java:130)
05-02 10:18:24.684  1616  1616 E EdXposed: 	at com.elderdrivers.riru.edxp.sandhook.core.SandHookRouter.startSystemServerHook(SandHookRouter.java:44)
05-02 10:18:24.684  1616  1616 E EdXposed: 	at com.elderdrivers.riru.edxp._hooker.impl.SystemMain.afterHookedMethod(SystemMain.java:27)
05-02 10:18:24.684  1616  1616 E EdXposed: 	at de.robv.android.xposed.XC_MethodHook.callAfterHookedMethod(XC_MethodHook.java:68)
05-02 10:18:24.684  1616  1616 E EdXposed: 	at com.swift.sandhook.xposedcompat.hookstub.HookStubManager.hookBridge(HookStubManager.java:393)
05-02 10:18:24.684  1616  1616 E EdXposed: 	at SandHookerNew_5p2l3n6isgb2am6fgc68b6ergp.hook(Unknown Source:45)
05-02 10:18:24.684  1616  1616 E EdXposed: 	at com.android.server.SystemServer.createSystemContext(SystemServer.java:671)
05-02 10:18:24.684  1616  1616 E EdXposed: 	at com.android.server.SystemServer.run(SystemServer.java:533)
05-02 10:18:24.684  1616  1616 E EdXposed: 	at com.android.server.SystemServer.main(SystemServer.java:391)
05-02 10:18:24.684  1616  1616 E EdXposed: 	at java.lang.reflect.Method.invoke(Native Method)
05-02 10:18:24.684  1616  1616 E EdXposed: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:549)
05-02 10:18:24.684  1616  1616 E EdXposed: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:917)
05-02 10:18:31.984  2113  2113 E EdXposed: can't access config path, using snapshot use_white_list: /data/user_de/0/com.android.bluetooth
05-02 10:18:31.984  2113  2113 E EdXposed: can't access config path, using snapshot black list: /data/user_de/0/com.android.bluetooth
05-02 10:18:32.035  2125  2125 E EdXposed: can't access config path, using snapshot use_white_list: /data/user_de/0/com.android.systemui
05-02 10:18:32.035  2125  2125 E EdXposed: can't access config path, using snapshot black list: /data/user_de/0/com.android.systemui
05-02 10:18:32.555  2269  2269 E EdXposed: can't access config path, using snapshot use_white_list: /data/user/0/com.breel.wallpapers18
05-02 10:18:32.555  2269  2269 E EdXposed: can't access config path, using snapshot black list: /data/user/0/com.breel.wallpapers18
05-02 10:18:32.634  2328  2328 E EdXposed: can't access config path, using snapshot use_white_list: /data/user_de/0/com.quicinc.cne.CNEService
05-02 10:18:32.634  2328  2328 E EdXposed: can't access config path, using snapshot black list: /data/user_de/0/com.quicinc.cne.CNEService
05-02 10:18:32.838  2368  2368 E EdXposed: can't access config path, using snapshot use_white_list: /data/user/0/com.google.android.grilservice
05-02 10:18:32.838  2368  2368 E EdXposed: can't access config path, using snapshot black list: /data/user/0/com.google.android.grilservice
05-02 10:18:33.138  2531  2531 E EdXposed: can't access config path, using snapshot use_white_list: /data/user_de/0/com.google.android.ext.services
05-02 10:18:33.138  2531  2531 E EdXposed: can't access config path, using snapshot black list: /data/user_de/0/com.google.android.ext.services
05-02 10:17:57.403  2699  2699 E EdXposed: can't access config path, using snapshot use_white_list: /data/user/0/com.google.android.gms
05-02 10:17:57.403  2699  2699 E EdXposed: can't access config path, using snapshot black list: /data/user/0/com.google.android.gms
05-02 10:18:00.694  2926  2926 E EdXposed: can't access config path, using snapshot use_white_list: /data/user/0/com.google.android.gms
05-02 10:18:00.694  2926  2926 E EdXposed: can't access config path, using snapshot black list: /data/user/0/com.google.android.gms
05-02 10:18:00.973  3052  3052 E EdXposed: can't access config path, using snapshot use_white_list: /data/user_de/0/com.android.cellbroadcastreceiver
05-02 10:18:00.973  3052  3052 E EdXposed: can't access config path, using snapshot black list: /data/user_de/0/com.android.cellbroadcastreceiver
05-02 10:18:01.050  3073  3073 E EdXposed: can't access config path, using snapshot use_white_list: /data/user_de/0/com.android.providers.blockednumber
05-02 10:18:01.050  3073  3073 E EdXposed: can't access config path, using snapshot black list: /data/user_de/0/com.android.providers.blockednumber
05-02 10:18:07.693  3484  3484 E EdXposed: can't access config path, using snapshot use_white_list: /data/user/0/com.google.android.providers.media.module
05-02 10:18:07.693  3484  3484 E EdXposed: can't access config path, using snapshot black list: /data/user/0/com.google.android.providers.media.module
05-02 10:18:07.837  3538  3538 E EdXposed: can't access config path, using snapshot use_white_list: /data/user/0/com.android.nfc
05-02 10:18:07.837  3538  3538 E EdXposed: can't access config path, using snapshot black list: /data/user/0/com.android.nfc
05-02 10:18:07.937  3587  3587 E EdXposed: can't access config path, using snapshot use_white_list: /data/user/0/com.google.SSRestartDetector
05-02 10:18:07.937  3587  3587 E EdXposed: can't access config path, using snapshot black list: /data/user/0/com.google.SSRestartDetector
05-02 10:18:08.040  3621  3621 E EdXposed: can't access config path, using snapshot use_white_list: /data/user/0/com.qualcomm.qti.services.secureui
05-02 10:18:08.040  3621  3621 E EdXposed: can't access config path, using snapshot black list: /data/user/0/com.qualcomm.qti.services.secureui
05-02 10:18:08.098  3651  3651 E EdXposed: can't access config path, using snapshot use_white_list: /data/user/0/com.google.android.gsf
05-02 10:18:08.098  3651  3651 E EdXposed: can't access config path, using snapshot black list: /data/user/0/com.google.android.gsf
05-02 10:18:09.596  4134  4134 E EdXposed: can't access config path, using snapshot use_white_list: /data/user/0/com.android.printspooler
05-02 10:18:09.596  4134  4134 E EdXposed: can't access config path, using snapshot black list: /data/user/0/com.android.printspooler
05-02 10:18:09.869  4185  4185 E EdXposed: can't access config path, using snapshot use_white_list: /data/user/0/com.android.providers.calendar
05-02 10:18:09.869  4185  4185 E EdXposed: can't access config path, using snapshot black list: /data/user/0/com.android.providers.calendar
05-02 10:18:10.455  4356  4356 E EdXposed: can't access config path, using snapshot use_white_list: /data/user/0/com.google.android.gsf
05-02 10:18:10.455  4356  4356 E EdXposed: can't access config path, using snapshot black list: /data/user/0/com.google.android.gsf
05-02 10:18:10.510  4458  4458 E EdXposed: can't access config path, using snapshot use_white_list: /data/user/0/com.google.android.partnersetup
05-02 10:18:10.510  4458  4458 E EdXposed: can't access config path, using snapshot black list: /data/user/0/com.google.android.partnersetup
05-02 10:18:11.231  4683  4683 E EdXposed: can't access config path, using snapshot use_white_list: /data/user/0/com.google.android.carriersetup
05-02 10:18:11.232  4683  4683 E EdXposed: can't access config path, using snapshot black list: /data/user/0/com.google.android.carriersetup
05-02 10:18:11.884  4879  4879 E EdXposed: can't access config path, using snapshot use_white_list: /data/user/0/com.android.providers.downloads
05-02 10:18:11.884  4879  4879 E EdXposed: can't access config path, using snapshot black list: /data/user/0/com.android.providers.downloads
05-02 10:18:16.844  5588  5588 E EdXposed: can't access config path, using snapshot use_white_list: /data/user/0/com.google.RilConfigService
05-02 10:18:16.844  5588  5588 E EdXposed: can't access config path, using snapshot black list: /data/user/0/com.google.RilConfigService
05-02 10:18:18.934  5865  5865 E EdXposed: can't access config path, using snapshot use_white_list: /data/user/0/com.android.managedprovisioning
05-02 10:18:18.934  5865  5865 E EdXposed: can't access config path, using snapshot black list: /data/user/0/com.android.managedprovisioning
05-02 10:18:20.998  6022  6022 E EdXposed: can't access config path, using snapshot use_white_list: /data/user/0/com.google.android.angle
05-02 10:18:20.998  6022  6022 E EdXposed: can't access config path, using snapshot black list: /data/user/0/com.google.android.angle
05-02 10:18:32.773  8789  8789 E EdXposed: can't access config path, using snapshot use_white_list: /data/user/0/com.android.chrome
05-02 10:18:32.773  8789  8789 E EdXposed: can't access config path, using snapshot black list: /data/user/0/com.android.chrome
05-02 10:18:33.166  8832  8832 E EdXposed: can't access config path, using snapshot use_white_list: /data/user/0/com.google.android.gms
05-02 10:18:33.166  8832  8832 E EdXposed: can't access config path, using snapshot black list: /data/user/0/com.google.android.gms
05-02 10:18:34.098  8971  8971 E EdXposed: can't access config path, using snapshot use_white_list: /data/user/0/com.google.android.gms
05-02 10:18:34.098  8971  8971 E EdXposed: can't access config path, using snapshot black list: /data/user/0/com.google.android.gms
05-02 10:18:35.216  9109  9109 E EdXposed: can't access config path, using snapshot use_white_list: /data/user/0/com.google.android.onetimeinitializer
05-02 10:18:35.216  9109  9109 E EdXposed: can't access config path, using snapshot black list: /data/user/0/com.google.android.onetimeinitializer
05-02 10:18:35.399  9136  9136 E EdXposed: can't access config path, using snapshot use_white_list: /data/user_de/0/com.google.android.packageinstaller
05-02 10:18:35.399  9136  9136 E EdXposed: can't access config path, using snapshot black list: /data/user_de/0/com.google.android.packageinstaller
05-02 10:18:35.625  9161  9161 E EdXposed: can't access config path, using snapshot use_white_list: /data/user/0/com.google.android.partnersetup
05-02 10:18:35.625  9161  9161 E EdXposed: can't access config path, using snapshot black list: /data/user/0/com.google.android.partnersetup
05-02 10:18:38.228  9428  9428 E EdXposed: can't access config path, using snapshot use_white_list: /data/user/0/com.google.android.storagemanager
05-02 10:18:38.228  9428  9428 E EdXposed: can't access config path, using snapshot black list: /data/user/0/com.google.android.storagemanager
05-02 10:18:38.797  9488  9488 D EdXposedManager: EdXposed is not active
05-02 10:18:38.798  9488  9488 D EdXposedManager: ApplicationList: Force add modules to list
05-02 10:18:39.124  9488  9488 D EdXposedManager: EdXposed is not active
05-02 10:18:42.999  9869  9869 E EdXposed: can't access config path, using snapshot use_white_list: /data/user/0/com.qualcomm.atfwd
05-02 10:18:42.999  9869  9869 E EdXposed: can't access config path, using snapshot black list: /data/user/0/com.qualcomm.atfwd
05-02 10:18:53.746 11266 11266 E EdXposed: can't access config path, using snapshot use_white_list: /data/user/0/com.android.chrome
05-02 10:18:53.746 11266 11266 E EdXposed: can't access config path, using snapshot black list: /data/user/0/com.android.chrome
05-02 10:18:57.594 11684 11684 E EdXposed: can't access config path, using snapshot use_white_list: /data/user/0/com.android.providers.calendar
05-02 10:18:57.594 11684 11684 E EdXposed: can't access config path, using snapshot black list: /data/user/0/com.android.providers.calendar
05-02 10:18:58.028 11742 11742 E EdXposed: can't access config path, using snapshot use_white_list: /data/user/0/com.android.externalstorage
05-02 10:18:58.028 11742 11742 E EdXposed: can't access config path, using snapshot black list: /data/user/0/com.android.externalstorage
05-02 10:18:58.187 11762 11762 E EdXposed: can't access config path, using snapshot use_white_list: /data/user/0/com.android.providers.downloads
05-02 10:18:58.187 11762 11762 E EdXposed: can't access config path, using snapshot black list: /data/user/0/com.android.providers.downloads
05-02 10:19:01.035 11839 11839 E EdXposed: can't access config path, using snapshot use_white_list: /data/user/0/com.google.android.partnersetup
05-02 10:19:01.035 11839 11839 E EdXposed: can't access config path, using snapshot black list: /data/user/0/com.google.android.partnersetup
05-02 10:19:05.984 12344 12344 E EdXposed: can't access config path, using snapshot use_white_list: /data/user/0/com.google.android.gms
05-02 10:19:05.984 12344 12344 E EdXposed: can't access config path, using snapshot black list: /data/user/0/com.google.android.gms
05-02 10:19:06.349 12421 12421 E EdXposed: can't access config path, using snapshot use_white_list: /data/user/0/com.google.android.gms
05-02 10:19:06.349 12421 12421 E EdXposed: can't access config path, using snapshot black list: /data/user/0/com.google.android.gms
05-02 10:19:17.597  9488  9488 D EdXposedManager: EdXposed is not active
05-02 10:19:17.599  9488  9488 I EdXposedManager: ModuleUtil -> updating modules.list
05-02 10:19:17.599  9488  9488 D EdXposedManager: EdXposed is not active
05-02 10:19:21.081  9488 12802 I EdXposedManager: RepoLoader -> Downloaded https://dl.xposed.info/repo/partial/18698.xml.gz with status 0 (error: null), size 66 bytes
05-02 10:19:21.085  9488 12802 I EdXposedManager: RepoLoader -> Updated repository https://dl-xda.xposed.info/repo/full.xml.gz to version 18698 (0 new / 0 removed modules)
05-02 10:20:12.218 12883 12883 E EdXposed: can't access config path, using snapshot use_white_list: /data/user/0/com.android.providers.contacts
05-02 10:20:12.218 12883 12883 E EdXposed: can't access config path, using snapshot black list: /data/user/0/com.android.providers.contacts
05-02 10:20:14.496 12925 12925 E EdXposed: can't access config path, using snapshot use_white_list: /data/user/0/com.android.providers.downloads
05-02 10:20:14.496 12925 12925 E EdXposed: can't access config path, using snapshot black list: /data/user/0/com.android.providers.downloads
05-02 10:20:17.020 12950 12950 E EdXposed: can't access config path, using snapshot use_white_list: /data/user/0/com.google.android.documentsui
05-02 10:20:17.020 12950 12950 E EdXposed: can't access config path, using snapshot black list: /data/user/0/com.google.android.documentsui
05-02 10:20:17.222 12972 12972 E EdXposed: can't access config path, using snapshot use_white_list: /data/user/0/com.android.externalstorage
05-02 10:20:17.222 12972 12972 E EdXposed: can't access config path, using snapshot black list: /data/user/0/com.android.externalstorage
```

**Comment by Justsnoopy30** [comment] 2020-05-17 17:09
@MlgmXyysd Any chance of a fix for this? Seems you're trying to hook something that doesn't exist or has changed in Android 11.

**Comment by kotori2** [comment] 2020-06-03 18:57
Cannot reproduce. I stucked at boot stage. 
My device is Pixel 4 XL with rpp4.200409.015
Some logs: 
![image](https://user-images.githubusercontent.com/17663689/83677497-d914e680-a60e-11ea-9226-b2f1ce01a334.png)

**Comment by Justsnoopy30** [comment] 2020-06-16 16:59
This issue happened on Android 11 DP3 (developer preview 3) when I last tried.

**Comment by Justsnoopy30** [comment] 2020-07-07 03:56
So... when is EdXposed gonna support Android 11?

**Comment by davidvhammond** [comment] 2020-09-01 17:24
I would love to know if Android 11 will be supported.

**Comment by kotori2** [comment] 2020-09-01 17:25
> I would love to know if Android 11 will be supported.

@davidvhammond 
https://github.com/ElderDrivers/EdXposed/tree/android_r

**Comment by abdallahabooda** [comment] 2020-09-12 19:28
When will it work on Android 11

**Comment by scq000** [comment] 2020-09-23 02:15
same problem

**Comment by 3c71** [comment] 2020-09-30 08:59
Did you try on riru core 21.3? 21.2 version shows "Works on Android R DP4". Maybe it'll work better?
https://github.com/RikkaApps/Riru/releases/tag/v21.3

**Comment by NuffsaidNL** [comment] 2020-10-01 09:59
> I would love to know if Android 11 will be supported.

> So... when is EdXposed gonna support Android 11?

> When will it work on Android 11

Come on guys... it's common sense you not gonna ask developers who dont charge you nothing for their products about ETA's. If you want to use it.. use a supported Android version. 
Even I'm annoyed by how easy there's being asked about ETAs on support for a not even finished version of Android. I can imagine developers getting even more annoyed by it.

And call me an old grumpy, but this is github.. not some telegram support channel or something.

**Comment by kotori2** [comment] 2020-11-24 13:08
If someone still didn't know, EdXposed already supports Android R from July, but it hasn't been merged into master branch yet. Canary builds will work on Android R.

**Closed by kotori2** 2020-11-24 13:08 UTC
Labels: bug

**Comment by chrisjf80** [comment] 2020-11-26 08:05
Developers are so miserable & aloof. Don't ask for help her this is GitHub not Telegram. Go play with Telegram & leave GitHub to the pro's. How dare u ask if an update is on it's way. U have no right to know that cause the developer is doing it for free. Yeah right. I'm sure the developers of exposed have done fine from it with all the back door revenue streams.
