### ISSUE TITLE
[BUG] Modules not activated after enabling App list mode

### ISSUE THREAD

**Issue by slimshouki** [ElderDrivers/EdXposed#675] opened 2020-11-27 13:33 UTC
**什么情况/What happened?** modules deactivated after enabling app list mode 

如无法开机/模块无效等

**Xposed模块列表/Xposed Module List** chromepie-unlimited call log-customizer-xposed edge pro-instapref-Wa tweaker-Nfg multi crack

允许截图/Screenshot allowed 
![IMG_20201127_152822](https://user-images.githubusercontent.com/74891073/100454292-49d02380-30c5-11eb-8e1d-4205f2aa5537.jpg)

**Magisk模块列表/Magisk Module List** riru core- edxposed - riru clipboard- gms doze

允许截图/Screenshot allowed 
![Screenshot_2020-11-27-15-28-37-249_iqgna twkk fy ms](https://user-images.githubusercontent.com/74891073/100454311-518fc800-30c5-11eb-94d7-ef459b8e70fe.jpg)

**EdXposed及Riru版本/Versions of EdXposed and Riru**

EdXposed: v0.5.0.6_4583

Riru: 22.4

**相关Logcat/Logcat**
[Verbose log](https://drive.google.com/file/d/1mDeExfnaX1XpcRk_42xpMAAZHFnRA-TV/view?usp=drivesdk) 
[Modules log](https://drive.google.com/file/d/1m8_-M29fzZ7eeVO43e85bJZTAMOrQ9ia/view?usp=drivesdk) 

有助于定位问题，必须使用我们的log抓取模块抓取/It can help us to locate issue, must use our logcat module

**Comment by kotori2** [comment] 2020-11-27 13:36
Everything looks fine from your logs

**Comment by slimshouki** [comment] 2020-11-27 13:37
> Everything looks fine from your logs

How come and modules not working if app list mode is on

Do you need more logs?

**Comment by kotori2** [comment] 2020-11-27 18:23
> How come and modules not working if app list mode is on

Modules loaded from your log.

**Comment by kotori2** [comment] 2020-11-27 18:24
If you actually referring #677 then my answer it's a won't fix.

**Comment by slimshouki** [comment] 2020-11-27 18:49
> If you actually referring #677 then my answer it's a won't fix. 

No its a different issue
1rst one happens when app list mode is off and modules are working but not fully.functional

This issue happens when app list mode is on and all modules is not working although they are loaded and framework is loaded

**Comment by kotori2** [comment] 2020-11-27 19:21
Can't reproduce. Recent YAHFA builds works good for me.

**Comment by kvxrun** [comment] 2020-11-29 12:02
facing same issue here, everything works perfectly with v4568 and riru v22 built by the edxposed team. but switching to any newer edxposed or riru version breaks the modules. using evolutionX android 11 on redmi note 7

**Comment by kotori2** [comment] 2020-11-29 12:09
@kvxrun It might break specific module, because we tightened SEPolicy and delayed some hooks. if your module stopped working even with global mode, submit issue to the module authors.

**Comment by yujincheng08** [comment] 2020-11-29 12:15
There's no actual "global" module. Only modules that apply to the system or system apps.

You don't actually have to hook the contacts most of the time.

**Closed** 2020-12-20 07:51 UTC
Labels: bug, module specific
