### ISSUE TITLE
[BUG] modules list not load

### ISSUE THREAD

**Issue by DvLAx3l** [ElderDrivers/EdXposed#374] opened 2019-10-22 09:28 UTC
Latest update doesn't load any module, it says can't load the module.list.
The module list is in the correct folder, the manager just doesn't load it.
It happens the same with the YAHFA version.

VERBOSE LOG
--------- beginning of head
EdXposed Log
Powered by Log Catcher
QQ chat group 855219808
--------- beginning of system info
Android version: 10
Android sdk: 29
Android build: QP1A.191005.007
Fingerprint: google/crosshatch/crosshatch:10/QP1A.191005.007/5878874:user/release-keys
ROM build description: crosshatch-user 10 QP1A.191005.007 5878874 release-keys
EdXposed Version: v0.4.6.0_beta(4471) (Sandhook)
Architecture: arm64-v8a
Device: crosshatch
Manufacture: Google
Brand: google
Product: crosshatch
--------- beginning of main
--------- beginning of system
01-08 22:31:53.380  1003  1003 I EdXposed: onModuleLoaded: welcome to EdXposed!
01-08 22:31:53.380  1003  1003 I EdXposed: Start to install inline hooks
01-08 22:31:53.380  1003  1003 I EdXposed: Using api level 29
01-08 22:31:53.380  1003  1003 I EdXposed: Start to install Riru hook
01-08 22:31:53.388  1003  1003 I EdXposed: Riru hooks installed
01-08 22:31:53.484  1003  1003 I EdXposed: ART hooks installed
01-08 22:31:53.484  1003  1003 I EdXposed: system_property_get: dalvik.vm.dex2oat-filter -> quicken
01-08 22:31:53.484  1003  1003 I EdXposed: system_property_get: dalvik.vm.dex2oat-flags -> --inline-max-code-units=0
01-08 22:31:53.852  1004  1004 I EdXposed: onModuleLoaded: welcome to EdXposed!
01-08 22:31:53.852  1004  1004 I EdXposed: Start to install inline hooks
01-08 22:31:53.852  1004  1004 I EdXposed: Using api level 29
01-08 22:31:53.852  1004  1004 I EdXposed: Start to install Riru hook
01-08 22:31:53.860  1004  1004 I EdXposed: Riru hooks installed
01-08 22:31:53.953  1004  1004 I EdXposed: ART hooks installed
01-08 22:31:53.954  1004  1004 I EdXposed: system_property_get: dalvik.vm.dex2oat-filter -> quicken
01-08 22:31:53.954  1004  1004 I EdXposed: system_property_get: dalvik.vm.dex2oat-flags -> --inline-max-code-units=0
01-08 22:31:53.992  1003  1003 I EdXposed: using installer org.meowcat.edxposed.manager
01-08 22:31:53.992  1003  1003 I EdXposed: black/white list mode: false, using whitelist: false
01-08 22:31:53.992  1003  1003 I EdXposed: dynamic modules mode: false
01-08 22:31:53.992  1003  1003 I EdXposed: resources hook: true
01-08 22:31:53.992  1003  1003 I EdXposed: deopt boot image: false
01-08 22:31:54.190  1004  1004 I EdXposed: using installer org.meowcat.edxposed.manager
01-08 22:31:54.190  1004  1004 I EdXposed: black/white list mode: false, using whitelist: false
01-08 22:31:54.190  1004  1004 I EdXposed: dynamic modules mode: false
01-08 22:31:54.190  1004  1004 I EdXposed: resources hook: true
01-08 22:31:54.190  1004  1004 I EdXposed: deopt boot image: false
01-08 22:31:55.662  1003  1003 E EdXposed-Bridge: Cannot load any modules because /data/user_de/0/org.meowcat.edxposed.manager/conf/modules.list was not found
10-22 11:24:49.483  1004  1004 E EdXposed-Bridge: Cannot load any modules because /data/user_de/0/org.meowcat.edxposed.manager/conf/modules.list was not found

MODULE LOG
--------- beginning of head
EdXposed Log
Powered by Log Catcher
QQ chat group 855219808
--------- beginning of system info
Android version: 10
Android sdk: 29
Android build: QP1A.191005.007
Fingerprint: google/crosshatch/crosshatch:10/QP1A.191005.007/5878874:user/release-keys
ROM build description: crosshatch-user 10 QP1A.191005.007 5878874 release-keys
EdXposed Version: v0.4.6.0_beta(4471) (Sandhook)
Architecture: arm64-v8a
Device: crosshatch
Manufacture: Google
Brand: google
Product: crosshatch
--------- beginning of main
--------- beginning of system
01-08 22:31:55.662  1003  1003 E EdXposed-Bridge: Cannot load any modules because /data/user_de/0/org.meowcat.edxposed.manager/conf/modules.list was not found
10-22 11:24:49.483  1004  1004 E EdXposed-Bridge: Cannot load any modules because /data/user_de/0/org.meowcat.edxposed.manager/conf/modules.list was not found

**Comment by Jacky-Bruse** [comment] 2019-10-22 10:56
I am the same with you,I follow the correct guidance.can you solve it ?

**Comment by kn007** [comment] 2019-10-23 01:25
Same issue for me. Now I am using back 0.4.5.5.
OnePlus 7 pro, Oxygen 10.0.1

**Comment by aiblockly** [comment] 2019-10-25 04:13
Same issue for me ,RedmiK20Pro MIUI11 Android 10
--------- beginning of head
EdXposed Log
Powered by Log Catcher
QQ chat group 855219808
--------- beginning of system info
Android version: 10
Android sdk: 29
Android build: QKQ1.190716.003
Fingerprint: Xiaomi/raphael/raphael:10/QKQ1.190716.003/V11.0.2.0.QFKCNXM:user/release-keys
ROM build description: raphael-user 10 QKQ1.190716.003 V11.0.2.0.QFKCNXM release-keys
EdXposed Version: v0.4.6.0_beta(4471) (Yahfa)
Architecture: arm64-v8a
Device: raphael
Manufacture: Xiaomi
Brand: Xiaomi
Product: raphael
--------- beginning of main
--------- beginning of system
--------- beginning of crash
10-25 12:09:45.476   722   722 E EdXposed-Bridge: Cannot load any modules because /data/user_de/0/org.meowcat.edxposed.manager/conf/modules.list was not found
10-25 12:09:57.548   723   723 E EdXposed-Bridge: Cannot load any modules because /data/user_de/0/org.meowcat.edxposed.manager/conf/modules.list was not found

**Comment by aiblockly** [comment] 2019-10-25 04:13
Same issue for me ,RedmiK20Pro MIUI11 Android 10
--------- beginning of head
EdXposed Log
Powered by Log Catcher
QQ chat group 855219808
--------- beginning of system info
Android version: 10
Android sdk: 29
Android build: QKQ1.190716.003
Fingerprint: Xiaomi/raphael/raphael:10/QKQ1.190716.003/V11.0.2.0.QFKCNXM:user/release-keys
ROM build description: raphael-user 10 QKQ1.190716.003 V11.0.2.0.QFKCNXM release-keys
EdXposed Version: v0.4.6.0_beta(4471) (Yahfa)
Architecture: arm64-v8a
Device: raphael
Manufacture: Xiaomi
Brand: Xiaomi
Product: raphael
--------- beginning of main
--------- beginning of system
--------- beginning of crash
10-25 12:09:45.476   722   722 E EdXposed-Bridge: Cannot load any modules because /data/user_de/0/org.meowcat.edxposed.manager/conf/modules.list was not found
10-25 12:09:57.548   723   723 E EdXposed-Bridge: Cannot load any modules because /data/user_de/0/org.meowcat.edxposed.manager/conf/modules.list was not found

**Comment by MlgmXyysd** [comment] 2019-10-26 02:01
use customized Magisk, change update channel in Magisk Manager and re-install it: http://edxp.meowcat.org/repo/version.json

**Comment by tuyennn** [comment] 2019-10-30 15:52
@MlgmXyysd, after add your custom update chanel.

![](https://i.imgur.com/5lyHjlU.jpg)

**Comment by MlgmXyysd** [comment] 2019-10-30 23:18
> @MlgmXyysd, after add your custom update chanel.
> 
> ![](https://camo.githubusercontent.com/aab375646833d5a71e89523dd110271a2070cef4/68747470733a2f2f692e696d6775722e636f6d2f356c79486a6c552e6a7067)

Caused by GitHub update SSL version, update bot crashed.
This bug will be fixed in the near future.

**Comment by huajijam** [comment] 2019-11-01 13:55
Same issue for me,OP6t OOS Android Q

**Comment by MlgmXyysd** [comment] 2019-11-04 06:54
Install customized Magisk manually

**Closed by MlgmXyysd** 2019-11-04 06:54 UTC
Labels: bug
